apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v2r9i5vt4-go 
  janus-idp.io/tekton: v2r9i5vt4-go
  backstage.io/kubernetes-id: v2r9i5vt4-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v2r9i5vt4-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  